participant_code = input("What is your participant code?")
file = open("Responses.txt", "w")
file.write(participant_code + "\n")
partner_code = 1
print("IF YOU PREFER NOT TO RESPOND TO A PARTICULAR QUESTION, RESPOND WITH '0'")
print("Please answer the following questions honestly")
print("What is your gender?")
P1_gender = input("Enter M or F: ")
file.write(P1_gender + "\n")
P1_age = input("What is your age?: ")
file.write(P1_age + "\n")
P1_ethnicity = input("What is your ethnicity?: ")
file.write(P1_ethnicity + "\n")
P1_marriage = input("Do you plan on getting married someday? \n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P1_marriage + "\n")
P1_children = input("Do you plan to have children someday? \n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P1_children + "\n")
P1_importance_of_sex = input("How important is sex to you in a relationship? \n 1 = Not at all important \n 2 = A little important \n 3 = Somewhat important \n 4 = Very Important \n 5 = Extremely Important \n")
file.write(P1_importance_of_sex + "\n")
P1_alcohol_frequency = input("How often do you prefer to drink alcohol? \n 1 = Never \n 2 = A few times a year \n 3 = A few times a month \n 4 = Once a week \n 5 = Daily \n")
file.write(P1_alcohol_frequency + "\n")
P1_novelty_seeking = input("How much do you typically enjoy trying new things? \n 1 = Nearly always dislike \n 2 = Usually dislike \n 3 = It depends \n 4 = Usually enjoy \n 5 = Nearly always enjoy \n")
file.write(P1_novelty_seeking + "\n")
P1_Communication = input("When you have a disagreement with someone, how soon do you prefer to discuss it with them? \n 1 = Never discuss \n 2 = Discuss eventually, if problem does not resolve on its own \n 3 = Discuss soon, after brief cooling off \n 4 = Discuss immediately \n ")
file.write(P1_Communication + "\n")
P1_Home_tidiness = input("How tidy do you typically keep your home? \n 1 = Very messy \n 2 = Somewhat Messy \n 3 = Neither messy nor tidy \n 4 = Somewhat tidy \n 5 = Very tidy \n")
file.write(P1_Home_tidiness + "\n")
P1_Religiosity = input("How religious are you? \n 1 = Not at all religious \n 2 = A little bit religious \n 3 = Somewhat religious \n 4 = Quite relgious \n 4 = Deeply religious \n")
file.write(P1_Religiosity + "\n")
P1_Likely_to_move_away = input("Do you plan to move out of Ontario someday?\n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P1_Likely_to_move_away + "\n")
P1_SexFreq = input("What is your ideal sexual frequency in a relationship? \n 1 = Never or almost never \n 2 = Once a month \n 3 = A few times a month \n 4 = Once a week \n 5 =  Twice a week \n 6 = A few times a week \n 7 = Daily \n ")
file.write(P1_SexFreq + "\n")
P1_Hobbies = input("What are your favorite hobbies? Please list up to three. \n")
file.write(P1_Hobbies + "\n")
P1_Activity_level = input("How much free time do you spend being active (i.e., out doing things) versus passive (e.g., TV, videogames)? \n 1 = Almost all passive \n 2 = More passive than active \n 3 = 50/50 \n 4 = More active than passive \n 5 = Almost all active \n")
file.write(P1_Activity_level + "\n")
P1_Financial_style = input("When you have extra cash, what do you prefer to do with it? \n 1 = Save it all \n 2 = Save most of it \n 3 = Save some, spend some \n 4 = Spend most of it \n 5 = Spend it all \n")
file.write(P1_Financial_style + "\n")
P1_Cat_attitudes = input("How do you feel about having a pet cat? \n 1 = Extremely negative \n 2 = Somewhat negative \n 3 = Neither positive nor negative \n 4 = Somewhat positive \n 5 = Extremely positive \n")
file.write(P1_Cat_attitudes + "\n")
P1_Political_Orientation = input("What is your political orientation? \n 1 = Extremely Conservative \n 2 = very conservative \n 3 = somewhat conservsative \n 4 = Not conservative nor libeal \n 5 = Somewhat liberal \n 6 = Very liberal \n 7 = Extremely liberal \n ")
file.write(P1_Political_Orientation + "\n")
P1_Urban_rural = input("How urban versus rural is your ideal neighbourhood?\n 1 = Very rural (in the boonies) \n 2 = Somewhat rural (small town) \n 3 = Both (suburbs) \n 4 = Somewhat urban (small city) \n 5 = Very urban (big city)\n ")
file.write(P1_Urban_rural + "\n")
P1_Physical_attraction = input("In a relationship, how important is physical attraction to you? \n 1 = Not at all important \n 2 = Slightly important \n 3 = Moderately important \n 4 = Very important \n 5 = Extremely important \n")
file.write(P1_Physical_attraction + "\n")
P1_marijuana = input("How often do you prefer to use cannabis recreationally? \n 1 = Never \n 2 = A few times a year \n 3 = Once a month \n 4 = A few times a month \n 5 = Once a week \n 6 = A few times a week \n 7 = Daily \n")
file.write(P1_marijuana + "\n")
P1_jealousy = input("Do you consider yourself to be a jealous person, romantically? \n 1 = Never jealous \n 2 = Rarely jealous \n 3 = Sometimes jealous \n 4 = Often jealous \n 5 = Always jealous \n")
file.write(P1_jealousy + "\n")
P1_Division_of_labour = input("How important is it to you tht household tasks are equally shared in a relationship? \n 1 = Not at all important \n 2 = Slightly important \n 3 = Moderately important \n 4 = Very important \n 5 = Extremely important \n")
file.write(P1_Division_of_labour + "\n")
P1_Dog_attitudes = input("How do you feel about having a pet dog? \n 1 = Extremely negative \n 2 = Somewhat negative \n 3 = Neither positive nor negative \n 4 = Somewhat positive \n 5 = Extremely positive \n")
file.write(P1_Dog_attitudes + "\n")
print("Please inform the research assistant that you have completed task 1")
print("IF YOU PREFER NOT TO RESPOND TO A PARTICULAR QUESTION, RESPOND WITH '0'")
print("Answer the following questions as if your partner might have access to them")
P2_marriage = input("Do you plan on getting married someday? \n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P2_marriage + "\n")
P2_children = input("Do you plan to have children someday? \n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P2_children + "\n")
P2_importance_of_sex = input("How important is sex to you in a relationship? \n 1 = Not at all important \n 2 = A little important \n 3 = Somewhat important \n 4 = Very Important \n 5 = Extremely Important \n")
file.write(P2_importance_of_sex + "\n")
P2_alcohol_frequency = input("How often do you prefer to drink alcohol? \n 1 = Never \n 2 = A few times a year \n 3 = A few times a month \n 4 = Once a week \n 5 = Daily \n")
file.write(P2_alcohol_frequency + "\n")
P2_novelty_seeking = input("How much do you typically enjoy trying new things? \n 1 = Nearly always dislike \n 2 = Usually dislike \n 3 = It depends \n 4 = Usually enjoy \n 5 = Nearly always enjoy \n")
file.write(P2_novelty_seeking + "\n")
P2_Communication = input("When you have a disagreement with someone, how soon do you prefer to discuss it with them? \n 1 = Never discuss \n 2 = Discuss eventually, if problem does not resolve on its own \n 3 = Discuss soon, after brief cooling off \n 4 = Discuss immediately \n ")
file.write(P2_Communication + "\n")
P2_Home_tidiness = input("How tidy do you typically keep your home? \n 1 = Very messy \n 2 = Somewhat Messy \n 3 = Neither messy nor tidy \n 4 = Somewhat tidy \n 5 = Very tidy \n")
file.write(P2_Home_tidiness + "\n")
P2_Religiosity = input("How religious are you? \n 1 = Not at all religious \n 2 = A little bit religious \n 3 = Somewhat religious \n 4 = Quite religious \n 5 = Deeply religious \n")
file.write(P2_Religiosity + "\n")
P2_Likely_to_move_away = input("Do you plan to move out of Ontario someday?\n 1 = Definitely not \n 2 = Probably not \n 3 = Maybe/Unsure \n 4 = Probably \n 5 = Definitely \n ")
file.write(P2_Likely_to_move_away + "\n")
P2_SexFreq = input("What is your ideal sexual frequency in a relationship? \n 1 = Never or almost never \n 2 = Once a month \n 3 = A few times a month \n 4 = Once a week \n 5 =  Twice a week \n 6 = A few times a week \n 7 = Daily \n ")
file.write(P2_SexFreq + "\n")
P2_Hobbies = input("What are your favorite hobbies? Please list up to three. \n")
file.write(P2_Hobbies + "\n")
P2_Activity_level = input("How much free time do you spend being active (i.e., out doing things) versus passive (e.g., TV, videogames)? \n 1 = Almost all passive \n 2 = More passive than active \n 3 = 50/50 \n 4 = More active than passive \n 5 = Almost all active \n")
file.write(P2_Activity_level + "\n")
P2_Financial_style = input("When you have extra cash, what do you prefer to do with it? \n 1 = Save it all \n 2 = Save most of it \n 3 = Save some, spend some \n 4 = Spend most of it \n 5 = Spend it all \n")
file.write(P2_Financial_style + "\n")
P2_Cat_attitudes = input("How do you feel about having a pet cat? \n 1 = Extremely negative \n 2 = Somewhat negative \n 3 = Neither positive nor negative \n 4 = Somewhat positive \n 5 = Extremely positive \n")
file.write(P2_Cat_attitudes + "\n")
P2_Political_Orientation = input("What is your political orientation? \n 1 = Extremely Conservative \n 2 = very conservative \n 3 = somewhat conservsative \n 4 = Not conservative nor libeal \n 5 = Somewhat liberal \n 6 = Very liberal \n 7 = Extremely liberal \n ")
file.write(P2_Political_Orientation + "\n")
P2_Urban_rural = input("How urban versus rural is your ideal neighbourhood?\n 1 = Very rural (in the boonies) \n 2 = Somewhat rural (small town) \n 3 = Both (suburbs) \n 4 = Somewhat urban (small city) \n 5 = Very urban (big city)\n ")
file.write(P2_Urban_rural + "\n")
P2_Physical_attraction = input("In a relationship, how important is physical attraction to you? \n 1 = Not at all important \n 2 = Slightly important \n 3 = Moderately important \n 4 = Very important \n 5 = Extremely important \n")
file.write(P2_Physical_attraction + "\n")
P2_marijuana = input("How often do you prefer to use cannabis recreationally? \n 1 = Never \n 2 = A few times a year \n 3 = Once a month \n 4 = A few times a month \n 5 = Once a week \n 6 = A few times a week \n 7 = Daily \n")
file.write(P2_marijuana + "\n")
P2_jealousy = input("Do you consider yourself to be a jealous person, romantically? \n 1 = Never jealous \n 2 = Rarely jealous \n 3 = Sometimes jealous \n 4 = Often jealous \n 5 = Always jealous \n")
file.write(P2_jealousy + "\n")
P2_Division_of_labour = input("How important is it to you tht household tasks are equally shared in a relationship? \n 1 = Not at all important \n 2 = Slightly important \n 3 = Moderately important \n 4 = Very important \n 5 = Extremely important \n")
file.write(P2_Division_of_labour + "\n")
P2_Dog_attitudes = input("How do you feel about having a pet dog? \n 1 = Extremely negative \n 2 = Somewhat negative \n 3 = Neither positive nor negative \n 4 = Somewhat positive \n 5 = Extremely positive \n")
file.write(P2_Dog_attitudes + "\n")
print("Please inform the research assistant that you are finished task 2. Do not touch the mouse or keyboard until you recieve instructions.")
file.write("\n\n")
file.close()
